#include <bits/stdc++.h>
#define For(type, i, a, b) for (type i = (a); i <= (b); ++i)
#define endl '\n'
using namespace std;

typedef long long ll;

const ll maxN = 1e18;
const ll minN = -1e18;
const ll MOD = 1e9 + 7;

const ll limit = 1e3 + 5;
const ll limit1 = 1e4 + 5;
const ll limit2 = 2e5 + 5;
const ll limit3 = 1e6 + 5;

void FastIn(){
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);
}

void ReadIn(){
    /*
    ll a, b;
    cin >> a >> b;
    cout << a / b;
    ll kd, hkd;
    ll res = (a - (a / b) * b) * 10 / b;
    kd = (a - (a / b) * b) * 10 / b;
    hkd = ((((a - (a / b) * b) * 10) - (b * res)) * 10) / b;
    if(kd != 0 && hkd != 0){
    cout << ".";
    cout << (a - (a / b) * b) * 10 / b;
    cout << ((((a - (a / b) * b) * 10) - (b * res)) * 10) / b;
    }
    */
    cout <<"Không có gì";
}
int main(){
    FastIn();
    ReadIn();
}
// 100 / 35
// 2
// (100 - (35*2)) *10 / 35
//
